apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "javaapp"
    spec:
      containers:
      - name: java
        image: demodaprregistry.azurecr.io/demodaprregistry:v3
        imagePullPolicy: Always
